spring:
  application:
    name: userService
#    DB Datasource
  datasource:
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:user_db}

#    Kafka Properties
  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}
    consumer:
      group-id: user-info-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.harsh.userService.deserializer.UserInfoDeserializer
    topic:
      name: user_service
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${USER_SERVICE_PORT:9810}




